module.exports = {
    employees: require('./employees'),
    genericgoods: require('./genericgoods'),
    productclasses: require('./productclasses'),
    products: require('./products'),
    boms: require('./boms'),
    purchaseorders: require('./purchaseorders'),
    purchasedetails: require('./purchasedetails'),
    suppliers: require('./suppliers'),   
    schedules: require('./schedules'),
    punchrecords: require('./punchrecords'),
    soprecords: require('./soprecords'),
    sopform: require('./sopform'),
    seats: require('./seats'),
    guides: require('./guides'),
    saleorders: require('./saleorders'),
    saledetails: require('./saledetails'),
    positions: require('./positions'),
    customization: require('./customization'),
    customclasses: require('./customclasses'),
    productcustom: require('./productcustom'),
}