module.exports = {
  employeesValidation: require("./employees"),
  genericgoodsValidation: require("./genericgoods"),
  productclassesValidation: require("./productclasses"),
  productsValidation: require("./products"),
  bomsValidation: require("./boms"),
  saleordersValidation: require("./saleorders"),
  saledetailsValidation: require("./saledetails"),
  salesValidation: require("./sales"),
  purchasedetailsValidation: require("./purchasedetails"),
  purchaseordersValidation: require("./purchaseorders"),
  purchasesValidation: require("./purchases"),
  suppliersValidation: require("./suppliers"),
  schedulesValidation: require("./schedules"),
  punchrecordsValidation: require("./punchrecords"),
  soprecordsValidation: require("./soprecords"),
  sopformValidation: require("./sopform"),
  seatsValidation: require("./seats"),
  guidesValidation: require("./guides"),
  positionsValidation: require("./positions"),
  customizationValidation: require("./customization"),
  customclassesValidation: require("./customclasses"),
  productcustomValidation: require("./productcustom"),
  ordersValidation: require("./orders").ordersValidation,
  orderdetailsValidation: require("./orders").orderdetailsValidation,
};
